--- 
environment_tier: production
default_region: us-east-1
region: "{% if override_region is defined %}{{ override_region }}{% else %}{{ default_region }}{% endif %}"
dns_points_to_load_balancer: "{{ load_balancers_enabled | bool }}"
